spring.application.name=x46-backend

spring.datasource.url=jdbc:postgresql://localhost:5434/x46
spring.datasource.username=x46
spring.datasource.password=x46

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080